services:
  wifes_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /data/postgres
    volumes:
      - ./postgres_data:/data/postgres
    ports:
      - "5431:5432"